### ISSUE TITLE
Imports show up as text kind in textDocument/documentSymbol

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/javascript-typescript-langserver#111]
![image](https://cloud.githubusercontent.com/assets/10532611/24211800/75293e80-0f2d-11e7-88c2-2b6e3eca3faa.png)

**Comment by alexsaveliev** [comment]
TS returns `alias` kind, which has no mapping in `SymbolKind` enum

**Comment by felixfbecker** [comment]
VS Code shows the same kind as for local variables
