### ISSUE TITLE
hover/refresh results in access error

### ISSUE THREAD

**Issue by aleksandersumowski** [sourcegraph/javascript-typescript-langserver#114]
I'm on a Mac, I'm using neovim with /autozimu/LanguageClient-neovim/. When attempting to eg textDocument/definition I get the following error message in response. Any suggestions? Directory /Library/Application Support/ApplePushService is only accessible as a root.
```json
{"code": -32603, "message": "Request textDocument/definition failed with message: EACCES: permission denied, scandir '/Library/Application Support/ApplePushService'"}
```

**Comment by felixfbecker** [comment]
What version of the LS are you running and what is the rootPath / rootUri being sent?

**Comment by aleksandersumowski** [comment]
You mean version of javascript-typescript-langserver? It's 1.2

How can I check rootPath / rootUri being sent?

**Comment by alexsaveliev** [comment]
@aleksandersumowski 

> How can I check rootPath / rootUri being sent?

Please run the server with `-t` to log requests/responses to console or with `-l file` to log them to a file. There should be `initialize` request which has either `rootPath` or `rootUri` parameter

Thanks!

**Comment by aleksandersumowski** [comment]
For the neovim plugin turns out the simple way to get debug information was to:
`:call LanguageClient_setLoggingLevel('DEBUG')`
before calling
`:LanguageClientStart`

The resulting log is:

23:10:08 INFO     Begin LanguageClientStart
23:10:08 INFO     End LanguageClientStart
23:10:08 INFO     Begin initialize
23:10:08 INFO     rootPath: /Users/aleksander.sumowski/projects/broadband-web
23:10:08 DEBUG     => {"jsonrpc": "2.0", "method": "initialize", "params": {"processId": 32092, "rootPath": "/Users/aleksander.sumowski/projects/broadband-web", "rootUri": "file:///Users/aleksander.sumowski/projects/broadband-web", "capabilities": {}}, "id": 0}
23:10:09 DEBUG     <= {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":1,"hoverProvider":true,"definitionProvider":true,"referencesProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"xworkspaceReferencesProvider":true,"xdefinitionProvider":true,"xdependenciesProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":["."]},"xpackagesProvider":true}}}
23:10:09 INFO     End initialize
23:10:09 DEBUG     <= {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"Background fetching failed  TypeError: uri.startsWith is not a function\n    at Object.uri2path (/usr/local/lib/node_modules/javascript-typescript-langserver/lib/util.js:85:13)\n    at LocalFileSystem.resolveUriToPath (/usr/local/lib/node_modules/javascript-typescript-langserver/lib/fs.js:54:51)\n    at LocalFileSystem.<anonymous> (/usr/local/lib/node_modules/javascript-typescript-langserver/lib/fs.js:58:57)\n    at Generator.next (<anonymous>)\n    at /usr/local/lib/node_modules/javascript-typescript-langserver/lib/fs.js:7:71\n    at __awaiter (/usr/local/lib/node_modules/javascript-typescript-langserver/lib/fs.js:3:12)\n    at LocalFileSystem.getWorkspaceFiles (/usr/local/lib/node_modules/javascript-typescript-langserver/lib/fs.js:57:16)\n    at FileSystemUpdater.<anonymous> (/usr/local/lib/node_modules/javascript-typescript-langserver/lib/fs.js:152:46)\n    at Generator.next (<anonymous>)\n    at /usr/local/lib/node_modules/javascript-typescript-langserver/lib/fs.js:7:71"}}
23:10:09 WARNING  register completion manager source failed.
23:10:09 INFO     textDocument/didOpen
23:10:09 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/didOpen", "params": {"textDocument": {"uri": "file:///Users/aleksander.sumowski/projects/broadband-web/app/assets/javascripts/actions.js", "languageId": "javascript", "version": 1, "text": "COMPLETE CODE FROM THE FILE"}}}
23:10:09 DEBUG     <= {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"Failed to fetch module structure:  { Error: EACCES: permission denied, scandir '/Library/Application Support/ApplePushService'\n  errno: -13,\n  code: 'EACCES',\n  syscall: 'scandir',\n  path: '/Library/Application Support/ApplePushService' }"}}
23:10:09 DEBUG     <= {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"Failed to fetch files for hover/definition for uri file://app/assets/javascripts/actions.js { Error: EACCES: permission denied, scandir '/Library/Application Support/ApplePushService'\n  errno: -13,\n  code: 'EACCES',\n  syscall: 'scandir',\n  path: '/Library/Application Support/ApplePushService' }"}}
23:10:15 INFO     textDocument/didChange
23:10:15 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/didChange", "params": {"textDocument": {"uri": "file:///Users/aleksander.sumowski/projects/broadband-web/app/assets/javascripts/actions.js", "version": 2}, "contentChanges": [{"text": "COMPLETE CODE FROM THE FILE"}]}}
23:10:15 INFO     textDocument/didChange
23:10:15 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/didChange", "params": {"textDocument": {"uri": "file:///Users/aleksander.sumowski/projects/broadband-web/app/assets/javascripts/actions.js", "version": 3}, "contentChanges": [{"text":}]}}
23:10:15 INFO     textDocument/didChange
23:10:15 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/didChange", "params": {"textDocument": {"uri": "file:///Users/aleksander.sumowski/projects/broadband-web/app/assets/javascripts/actions.js", "version": 4}, "contentChanges": [{"text":}]}}
23:10:15 INFO     textDocument/didChange
23:10:15 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/didChange", "params": {"textDocument": {"uri": "file:///Users/aleksander.sumowski/projects/broadband-web/app/assets/javascripts/actions.js", "version": 5}, "contentChanges": [{"text":}]}}
23:10:15 INFO     textDocument/didChange
23:10:15 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/didChange", "params": {"textDocument": {"uri": "file:///Users/aleksander.sumowski/projects/broadband-web/app/assets/javascripts/actions.js", "version": 6}, "contentChanges": [{"text":}]}}
23:10:16 INFO     textDocument/didChange
23:10:16 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/didChange", "params": {"textDocument": {"uri": "file:///Users/aleksander.sumowski/projects/broadband-web/app/assets/javascripts/actions.js", "version": 7}, "contentChanges": [{"text":}]}}
23:10:17 INFO     textDocument/didChange
23:10:17 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/didChange", "params": {"textDocument": {"uri": "file:///Users/aleksander.sumowski/projects/broadband-web/app/assets/javascripts/actions.js", "version": 8}, "contentChanges": [{"text":}]}}
23:10:19 INFO     textDocument/didChange
23:10:19 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/didChange", "params": {"textDocument": {"uri": "file:///Users/aleksander.sumowski/projects/broadband-web/app/assets/javascripts/actions.js", "version": 9}, "contentChanges": [{"text":}]}}
23:10:23 INFO     Begin textDocument/definition
23:10:23 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/definition", "params": {"textDocument": {"uri": "file:///Users/aleksander.sumowski/projects/broadband-web/app/assets/javascripts/actions.js"}, "position": {"line": 14, "character": 8}}, "id": 1}
23:10:23 DEBUG     <= {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"Failed to fetch module structure:  { Error: EACCES: permission denied, scandir '/Library/Application Support/ApplePushService'\n  errno: -13,\n  code: 'EACCES',\n  syscall: 'scandir',\n  path: '/Library/Application Support/ApplePushService' }"}}
23:10:23 DEBUG     <= {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"Failed to fetch files for hover/definition for uri file://app/assets/javascripts/actions.js { Error: EACCES: permission denied, scandir '/Library/Application Support/ApplePushService'\n  errno: -13,\n  code: 'EACCES',\n  syscall: 'scandir',\n  path: '/Library/Application Support/ApplePushService' }"}}
23:10:23 DEBUG     <= {"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Request textDocument/definition failed with message: EACCES: permission denied, scandir '/Library/Application Support/ApplePushService'"}}
23:10:23 ERROR    {"jsonrpc": "2.0", "id": 1, "error": {"code": -32603, "message": "Request textDocument/definition failed with message: EACCES: permission denied, scandir '/Library/Application Support/ApplePushService'"}}

**Comment by alexsaveliev** [comment]
@aleksandersumowski could you please add some debug to see what are the root path and pattern when LSP server searching for files?

something like
```
diff --git a/src/fs.ts b/src/fs.ts
index 2ec407e..867d8e3 100644
--- a/src/fs.ts
+++ b/src/fs.ts
@@ -64,6 +64,7 @@ export class LocalFileSystem implements FileSystem {
 
 	async getWorkspaceFiles(base?: string): Promise<string[]> {
 		const pattern = base ? path.posix.join(this.resolveUriToPath(base), '**/*.*') : this.resolveUriToPath('file:///**/*.*');
+		console.error("base =", base, "pattern =", pattern);
 		const files = await new Promise<string[]>((resolve, reject) => {
 			glob(pattern, { nodir: true }, (err, matches) => err ? reject(err) : resolve(matches));
 		});
```

Also, are there any symlinks in `/Users/aleksander.sumowski/projects/broadband-web/`?

Thanks!

**Comment by aleksandersumowski** [comment]
Took bit of time as simple console.log didn't work for me. Had to pass logger to the method. Anyways, the information you asked for is:

base = undefined pattern = /**/*.*

**Comment by felixfbecker** [comment]
I think we should have a test for working with a non-root root URI.

**Comment by aleksandersumowski** [comment]
can i work around the bug then? or should there be a fix in LanguageClient-neovim to pass some other `base` value? or `rootUri`?

**Comment by felixfbecker** [comment]
@aleksandersumowski I'm afraid I will have to look into this to find a fix. Did you try the newest release?

**Comment by alexsaveliev** [comment]
supposed to be fixed by #132 
@aleksandersumowski could you please try with 2.0.0-pre.9?

Thanks!

**Comment by aleksandersumowski** [comment]
It seems that there are still some issues. This is what debug log spits out:

```
16:22:44 INFO     Begin textDocument/definition
16:22:44 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/definition", "params": {"textDocument": {"uri": "file:///Users/aleksander.sumowski/projects/broadband-web/app/assets/javascripts/actions.js"}, "position": {"line": 11, "character": 10}}, "id": 6}
16:22:52 DEBUG     <= {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"Failed to fetch module structure:  URIError: URI malformed\n    at decodeURIComponent (<anonymous>)\n    at Array.map (native)\n    at Object.uri2path (/Users/aleksander.sumowski/projects/javascript-typescript-langserver/lib/util.js:93:30)\n    at InMemoryFileSystem.add (/Users/aleksander.sumowski/projects/javascript-typescript-langserver/lib/project-manager.js:574:63)\n    at FileSystemUpdater.<anonymous> (/Users/aleksander.sumowski/projects/javascript-typescript-langserver/lib/fs.js:131:37)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/aleksander.sumowski/projects/javascript-typescript-langserver/lib/fs.js:4:58)"}}
16:22:52 DEBUG     <= {"jsonrpc":"2.0","id":6,"error":{"code":-32603,"message":"Request textDocument/definition failed with message: URI malformed"}}
16:22:52 ERROR    {"jsonrpc": "2.0", "id": 6, "error": {"code": -32603, "message": "Request textDocument/definition failed with message: URI malformed"}}
```

**Comment by alexsaveliev** [comment]
@aleksandersumowski 

could you please : 
- checkout `as/bughunt` branch
- compile it by running `yarn && yarn build`
- adjust neovim plugin settings to run LSP server with the additional `-t -f /path-to-file` arguments
- repeat this issue
- attach content of `/path-to-file`

I will try to see what URI is considered malformed and why

Thanks!

**Comment by aleksandersumowski** [comment]
I'll do that in the evening

**Comment by aleksandersumowski** [comment]
Sorry for not checking earlier. This now works with the master!
