### ISSUE TITLE
Pass WorkspaceSymbolParams.limit to getNavigateToItems() as maxResultCount

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/javascript-typescript-langserver#123]
Limit is currently only done after getting the result with `slice()`. This could yield a performance boost for a workspace/symbol with limit.

Streaming could also be hacked by first asking for ~20 symbols and returning these as partial result, then asking for the rest and returning them.

**Comment by alexsaveliev** [comment]
I think that your changes were incorrect.
Symbols may be searched in a few locations (based on project configurations). If there are 2 tsconfig.json files, then you'll have `2 x number` of symbols (if there are at least number symbols in each project configuration). `slice` ensures that when all symbols from all locations are merged there will be only N left. I think you should decrease counter after each configuration until it becomes 0

**Comment by felixfbecker** [comment]
You are right, we may still return more symbols than the limit now. But it's better than before :)

**Comment by alexsaveliev** [comment]
Why not use remainder as a limit? Fetch up to TOTAL items from config 1 (let's it be N), then fetch up to TOTAL - N items from config 2 and so on. until remainder is 0 or there are no more configs?
