### ISSUE TITLE
Jump to definition should highlight just the identifier, not the entire function body

### ISSUE THREAD

**Issue by beyang** [sourcegraph/javascript-typescript-langserver#127]
Repro:
- https://sourcegraph.com/github.com/angular/angular@309bae0a0b2f584630a2a5db8f39557513a021ba/-/blob/aio/aio-builds-setup/dockerbuild/scripts-js/lib/verify-setup/helper.ts#L11:29-11:38
- Click "Jump to def"
- Got:
![image](https://cloud.githubusercontent.com/assets/1646931/24626396/0a41d720-1866-11e7-90bd-b311e6202960.png)
- Expected:
![image](https://cloud.githubusercontent.com/assets/1646931/24626405/13360928-1866-11e7-856c-745a2d1c1cd1.png)

**Comment by felixfbecker** [comment]
I agree, but I'm afraid that is what TS returns...

**Comment by felixfbecker** [comment]
I think we may be able to solve this by using the TS compiler API to get the node at the position.
If not, we can shorten it to the next space.

cc @alexsaveliev

**Comment by alexsaveliev** [comment]
not sure if there is such an API, probably we should extract first non-reserved word from document's substring using boundaries returned by TS

**Comment by felixfbecker** [comment]
![image](https://cloud.githubusercontent.com/assets/10532611/25054083/80e6f47a-215b-11e7-8cd9-1c9204684f4b.png)

When I tried to repro it also included the `export class` in the selection. I would try to get the node at that offset and find the first child node that is a `Identifier`.

**Comment by akhleung** [comment]
We had similar issues with Java. Ended up having to get the positions of the nearest symbols surrounding what we wanted to highlight, and then do a substring search.

**Comment by felixfbecker** [comment]
The repro is fixed
