### ISSUE TITLE
Do not terminate server on "exit" when number of workers is 1

### ISSUE THREAD

**Issue by alexsaveliev** [sourcegraph/javascript-typescript-langserver#130]
- Try to run server when number of workers is 1
- Upon reception of `exit` request (for example switch folder in VS Code) server dies

-> I think it shouldn't

**Comment by felixfbecker** [comment]
Actually, it shouldn't: https://sourcegraph.com/github.com/sourcegraph/javascript-typescript-langserver@master/-/blob/src/server.ts#L31:1-32:1

cluster size == 1 is only really for debugging.

**Comment by alexsaveliev** [comment]
As discussed in Slack:

> if sourcegraph is running locally with STDIO langservers, does it send `exit` notifications and expect the LS to _not_ exit?

>> it expects it to exit, but will force kill if it doesn't
