### ISSUE TITLE
Add Streaming Support

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/javascript-typescript-langserver#150]
https://github.com/Microsoft/language-server-protocol/pull/182

The underlying TypeScript service doesn't support this, but we could achieve some streaming on our layer:
- First ask for e.g. 20 workspace symbols and emit the partial result, then ask for all and emit the rest
- Fetch & compile files incrementally and stream new references found

The foundations for this are all there with the introduction of Observables into the codebase.

**Comment by lindaxie** [comment]
Tracking this issue in Sourcegraph's main repo. Closing.
