### ISSUE TITLE
Fails to resolve triple-slash reference

### ISSUE THREAD

**Issue by tomv564** [sourcegraph/javascript-typescript-langserver#169]
Starting up the service against this codebase reproduces the issue, I am calling initialize with:

```
initialize {'rootUri': 'file:///Users/tomv/Projects/sourcegraph/javascript-typescript-langserver'} 
```

When processing the triple-slash reference to thenable.d.ts in `vscode-jsonrpc/lib/main.d.ts`:

ProjectManager converts this reference to a relative path (`node_modules/vscode-jsonrpc/lib/thenable.d.ts`) at https://github.com/sourcegraph/javascript-typescript-langserver/blob/master/src/project-manager.ts#L350,

which is later converted to an the URI `file://node_modules/vscode-jsonrpc/lib/thenable.d.ts` at https://github.com/sourcegraph/javascript-typescript-langserver/blob/master/src/project-manager.ts#L362

The following error is logged by the process:
```
Error resolving file references for file:///Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/vscode-jsonrpc/lib/main.d.ts: { Error: ENOENT: no such file or directory, open '/node_modules/vscode-jsonrpc/lib/thenable.d.ts'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/node_modules/vscode-jsonrpc/lib/thenable.d.ts' } 
```

**Comment by felixfbecker** [comment]
Thanks for filing & debugging this! It clearly should not not be converted to a relative path, this must be an artifact of a refactor to URIs.

**Comment by tomv564** [comment]
Very closely related, the `/// <reference types="node"/>` imports are also not being picked up by project-manager.

This directive is documented at [The Typescript Handbook](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Triple-Slash%20Directives.md).
It can be read from `info.typeReferenceDirectives` and resolved using the Typescript helper: `ts.resolveTypeReferenceDirective`

Implementing both forms of the triple-slash reference allows the language server to successfully start up against its own source.

**Comment by tomv564** [comment]
I started poking at writing a test for this case, I can create a PR today or tomorrow.

**Comment by felixfbecker** [comment]
Triple slash references should be resolved in general.
