### ISSUE TITLE
Completions / hover never uses updated content after initial didOpen

### ISSUE THREAD

**Issue by tomv564** [sourcegraph/javascript-typescript-langserver#170]
Repro:
1. Open a TS file (triggers didOpen) 
2. Hover over a variable, observe the correct information is returned
3. Rename the variable (triggers didChange with incrementing version number  1, 2, 3, ...)
4. Hover again: Observe the original name of the variable is returned.
5. Save the document (triggers didSave)
6. Hover again: Observe the original name is still returned

Only when the server is restarted does the hover return the new name.

I tried this (originally with completions) on a few different commits, it stopped working where the ensureFiles refactor was merged (https://github.com/sourcegraph/javascript-typescript-langserver/pull/151)

**Comment by felixfbecker** [comment]
Thanks for filing, could you provide an LSP message log (see `--trace`, `--logfile`) so we can see what URIs your client sent? Thanks!

**Comment by tomv564** [comment]
Log attached here: [lspserver.txt](https://github.com/sourcegraph/javascript-typescript-langserver/files/923049/lspserver.txt)

**Comment by alexsaveliev** [comment]
claimed fixed by #175
