### ISSUE TITLE
Server hangs on Windows when called from VS Code

### ISSUE THREAD

**Issue by alexsaveliev** [sourcegraph/javascript-typescript-langserver#171]
- start LSP server and connect to it from VS Code (i.e. to see hover)
- Server receives URI such a `file:///d%3A/tmp/javascript-typescript-langserver/node_modules/vscode-jsonrpc/lib/main.d.ts`
- url.parse() returns 
```
Url {
  protocol: 'file:',
  slashes: true,
  auth: null,
  host: '',
...
  pathname: '/d%3A/tmp/javascript-typescript-langserver/node_modules/vscode-json
rpc/lib/main.d.ts',
...
```
and then server enters infinite loop in `getConfiguration()` because of the trailing slash (condition `dir !== this.rootPath)` is never met, there is no entry that starts with slash.

**Comment by tomv564** [comment]
Is it #172 that takes care of this issue? Manually applying the commits in that PR fixes my issues on Windows, would love it if a temporary fix could be merged before the greater path handling inconsistencies are tackled!

**Comment by felixfbecker** [comment]
Hey @tomv564 I added tests for running with a Windows-style `rootUri` like `file:///c:/foo/bar/` and  all tests pass on master in Travis and AppVeyor. A failing test case would be awesome!

https://github.com/sourcegraph/javascript-typescript-langserver/commit/86f7223ffbc4635e18868ec43536abfc612890ac#diff-bb5fc94acd70d49affe07c4866addcc2R6

**Comment by tomv564** [comment]
I see no hangs at startup on Windows anymore :+1:
