### ISSUE TITLE
Replace getNavigateToItems() with getNavigationBarItems() for an empty query

### ISSUE THREAD

**Issue by alexsaveliev** [sourcegraph/javascript-typescript-langserver#18]
We are using forked TypeScript library to enable `getNavigateToItems('')`. Can't we achieve the same results with `getNavigationBarItems()` plus some post-processing?
This is the only thing that blocks us from switching back to upstream TypeScript after [experimental branch](/alexsaveliev/javascript-typescript-langserver/tree/updating-host-files) wll be merged.

Note that question about possibility to use empty query has been already raised here Microsoft/TypeScript#2500

**Comment by sqs** [comment]
I don't have any special knowledge here.
