### ISSUE TITLE
Slow load time on repo page 

### ISSUE THREAD

**Issue by lindaxie** [sourcegraph/javascript-typescript-langserver#187]
Repro
- open https://sourcegraph.com/github.com/Microsoft/TypeScript 
- notice now it takes 3-4 seconds to load repo land
- see video: https://cl.ly/2i1W2D190q2h

**Comment by felixfbecker** [comment]
Pretty sure this is not the language server's fault

**Comment by felixfbecker** [comment]
This issue was moved to sourcegraph/sourcegraph#5425
