### ISSUE TITLE
Cross repo peek definition highlights entire definition, not just identifier

### ISSUE THREAD

**Issue by lindaxie** [sourcegraph/javascript-typescript-langserver#188]
Repro:
- go to https://sourcegraph.com/github.com/angular-ui/ui-router/-/blob/src/stateProvider.ts#L25:5-25:25
- peek defintion on createProxyFunctions
- notice how the entire definition is highlighted https://cl.ly/3Z3i0s0q2F2H, not just the identifier
- also notice how the side panel does not pop up given the highlighted area

**Comment by alexsaveliev** [comment]
duplicates #127

**Comment by felixfbecker** [comment]
I will keep this open to track the user-facing issue. The underlying bug is tracked by https://github.com/sourcegraph/javascript-typescript-langserver/issues/102.
