### ISSUE TITLE
Workspace symbol not fully working in palantir/tslint

### ISSUE THREAD

**Issue by lindaxie** [sourcegraph/javascript-typescript-langserver#189]
Repro:
- Go to https://sourcegraph.com/github.com/palantir/tslint
- Issue a workspace/symbol query for "#getFileNames" --> "No symbols matching"
- text search for getFileNames
- notice how getFileNames is defined in tslint but can't be found with Quick Open 
- see screenshot https://cl.ly/361u0z0H2A08

**Comment by felixfbecker** [comment]
Cannot repro. Maybe a race condition?

**Comment by lindaxie** [comment]
Yeah, I got the same thing just now. Closing for now, we can reopen if this comes up again.

**Comment by felixfbecker** [comment]
Happening again. Empty query also returns no result.

![image](https://cloud.githubusercontent.com/assets/10532611/25276304/d63f66b2-2699-11e7-9796-8c1563953995.png)

Trace: https://app.lightstep.com/sourcegraph-prod/trace?span_guid=1d95915d70975459&at_micros=1492775532231768#span-1d95915d70975459

**Comment by beyang** [comment]
Happened for me just now, too.

**Comment by lindaxie** [comment]
Workspace symbols are working in palantir/tslint. Closing for now, we can reopen if this comes up again.
