### ISSUE TITLE
Identifier appears twice in Quick Open search 

### ISSUE THREAD

**Issue by lindaxie** [sourcegraph/javascript-typescript-langserver#190]
Repro:
- go to https://sourcegraph.com/github.com/angular-ui/ui-router
- open Quick Open and search for #makecomponenttemplate 
- notice how it appears twice in the Quick Open search results https://cl.ly/1E28350j1L3x and both results take you to the same definition

**Comment by felixfbecker** [comment]
@alexsaveliev still happening. Should get a test

**Comment by alexsaveliev** [comment]
@felixfbecker this happens because there are **two** servers (javascript and typescript) that return the same data. I think that results should be filtered to leave only distinct items or only one server from TS/JS pair should be called.

**Comment by felixfbecker** [comment]
This would only be solved by https://github.com/sourcegraph/sourcegraph/issues/5401 then, but I would require major changes I would like to defer to the JS GA.

@lindaxie how common was this issue? Would it be acceptable to leave this as is for now?

**Comment by lindaxie** [comment]
@felixfbecker I've only seen it once or twice but I haven't spent a lot of time testing workspace symbol search so it could be common. However, it's doesn't affect the user's ability to user Sourcegraph, it just looks strange and can be confusing for the user (hence P2).

Yes, we can defer this issue until JS GA.
