### ISSUE TITLE
what's the transfer protocol?

### ISSUE THREAD

**Issue by mickaelistria** [sourcegraph/javascript-typescript-langserver#196]
I'm trying to replace using of the LS over stdio by the regular one, over some ports. However, I fail at identifying the connection kind that should be used: TCP, UDP, WebSockets...? Can you please clarify that in README.md?

**Comment by felixfbecker** [comment]
The STDIO version is the "regular" one, the other version is using TCP to support multiple clients. This could be better highlighted in the README, feel free to do a PR
