### ISSUE TITLE
Workspace/symbol on the target repo can’t find the symbol

### ISSUE THREAD

**Issue by lindaxie** [sourcegraph/javascript-typescript-langserver#198]
Some examples
- [x] https://sourcegraph.com/github.com/angular-ui/ui-router/-/blob/src/stateProvider.ts#L25:5-25:25 _Cause: package names don't match_ 
- [x] https://sourcegraph.com/github.com/Microsoft/vscode/-/blob/extensions/git/src/merge.ts#L22:29-22:41 _Cannot repro_ 
- [x] https://sourcegraph.com/github.com/angular-ui/ui-router/-/blob/src/stateProvider.ts#L118:31-118:40 _Cause: package names don't match_
- [x] https://sourcegraph.com/github.com/DefinitelyTyped/DefinitelyTyped/-/blob/types/acl/test/mongodbBackend.ts#L8:27-8:41 _Cannot repro_
- [x]  https://sourcegraph.com/github.com/DefinitelyTyped/DefinitelyTyped/-/blob/types/acl/index.d.ts#L21:56-21:70 _Cannot repro_
- [x] https://sourcegraph.com/github.com/NativeScript/NativeScript/-/blob/apps/app/cuteness.io/app.ts#L9:13-9:18 _Cause: nested package.jsons_
- [x] https://sourcegraph.com/github.com/angular-ui/ui-router/-/blob/src/urlRouterProvider.ts#L33:30-33:39 _Cause: package names don't match_

**Comment by felixfbecker** [comment]
Tracked in individual issues
