### ISSUE TITLE
Large amount of diagnostics due to module resolution issues

### ISSUE THREAD

**Issue by tomv564** [sourcegraph/javascript-typescript-langserver#208]
Opening this repo causes a large volume of diagnostics which VS Code / tsc does not show.
```
node_modules/@reactivex/rxjs/typings/globals/node/index.d.ts:
All declarations of 'WeakMap' must have identical type parameters.
```
(caused by Rxjs including typings in the package, fixed by @felixfbecker at https://github.com/ReactiveX/rxjs/issues/2561)

```
src/connection.ts:
File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/Rx.d.ts' is not a module.
```
Could this second issue be caused by the TS checker not getting file contents for that path?

**Comment by felixfbecker** [comment]
We could ignore diagnostics from node_modules.

Don't know about the second one.

**Comment by tomv564** [comment]
The `syncProgram` call in ProjectConfiguration's `init` causes the compiler to start requesting modules before `ensureReferencedFiles` has had a chance to load content for them. Commenting it out appears to fix the problem. We could try to remove that sync and make sure other paths force a sync if they don't require references/imports to be loadable.

**Comment by felixfbecker** [comment]
Sounds more like `init` is called to early for me?

**Comment by tomv564** [comment]
Narrowed it down a bit further. Commenting out the sync in `init` helped because it caused `ensureBasicFiles` to early-out until the references were fetched.

Logging reveals that `ensureBasicFiles` is adding the generated declarations (e.g.  lib/lang-handler.d.ts) as source files, which are then picked up by the TS compiler.
Filtering out lib/ in ensureBasic files prevents the diagnostics storm. 

Should `ensureBasicFiles` observe the tsconfig's `includes` directive? Should it even be adding non-global declarations that are not referenced to in some way?

**Comment by tomv564** [comment]
The typescript compiler is also unsuccessfully requesting these two files. This is when the references for a Rxjs have already been resolved.
```
node_modules/@reactivex/rxjs/dist/cjs/add/observable/if.d.ts MISSING 
node_modules/@reactivex/rxjs/dist/cjs/add/observable/throw.d.ts MISSING
```

**Comment by tomv564** [comment]
^^^ This was a false alarm - I was logging empty files as missing.

**Comment by tomv564** [comment]
This is what I see when I didOpen `typescript-service.ts` in this project:

**Compiler diagnostics** (not reported, I added code to log these)
```
5055: Cannot write file '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/lib/ast.d.ts' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig. 

^^^ many more of these for every .ts file in /lib ^^^

6053: File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@types/node/LICENSE.ts' not found. 
6054: File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@types/node/README.md' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. 
6054: File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@types/node/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. 
```

I believe it is the `ensureBasicFiles` behaviour I commented about above that causes these diagnostics, but they might otherwise be harmless.

**File diagnostics**

```
src/typescript-service.ts:
	1:28    	lsp     	error   	File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/Rx.d.ts' is not a module.
	4:22    	lsp     	error   	File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/opentracing/lib/index.d.ts' is not a module.
	26:8    	lsp     	error   	File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/vscode-languageserver/lib/main.d.ts' is not a module.
	37:2    	lsp     	error   	'InitializeResult' is declared but never used.
	39:2    	lsp     	error   	'PackageInformation' is declared but never used.
	40:2    	lsp     	error   	'ReferenceInformation' is declared but never used.
	42:2    	lsp     	error   	'SymbolLocationInformation' is declared but never used.
	151:14  	lsp     	error   	Property 'rootUri' does not exist on type 'InitializeParams'.
```

These diagnostics are a bigger problem - when TS cannot resolve `Observable<InitializeResult>` then it also claims `InitializeResult` is unused.
I believe TS gets in this state when the language service host replies "yes, I have this file, but it is empty". The content preloading mechanism in ensureReferencedFiles _should_ be taking care of this, but it doesn't.

**Comment by tomv564** [comment]
Are you seeing these diagnostics too @felixfbecker ? 

I made two changes:
* Add `mocha` to the global TS regexes (for #220)
* Only add files from `expFiles` or `node_modules` in `ensureBasicFiles`

And now the file diagnostics disappeared. 

The remaining compiler diagnostics are now:
```
6053: File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@types/mocha/LICENSE.ts' not found. 
6053: File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@types/node/LICENSE.ts' not found. 
6054: File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@types/mocha/README.md' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. 
6054: File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@types/mocha/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. 
6054: File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@types/node/README.md' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. 
6054: File '/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@types/node/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. 
```

I can provide a pull request to clean all the compiler diagnostics from `ensureBasicFiles` up later today, please comment if the `expFiles` fix makes sense.

**Comment by felixfbecker** [comment]
I am testing the LS with the test suite and the integration into Sourcegraph and we don't show diagnostics, so this is hard for me test (if there is no failing unit test).

> Only add files from expFiles or node_modules in ensureBasicFiles

iirc it used to be that way but was changed because files were missing. It doesn't make sense to add  markdown files of course. I would try to find that commit with git blame and see if that case is still handled / solved better in a different way.

**Comment by tomv564** [comment]
Bypassing `expFiles` was done in https://github.com/sourcegraph/javascript-typescript-langserver/pull/200, which unfortunately has no test case or issue to explain which paths in a project were missed.

The markdown files are added because neither LocalFileSystem's `getWorkspaceFiles` nor `getScriptFileNames` in the LanguageServiceHost filter them out.

**Comment by felixfbecker** [comment]
> when adding basic files, searching for them project-wide instead of searching in expected files list. The reason is that files may be excluded by tsconfig.json rule

Don't know what exactly was meant by that though.

**Comment by tomv564** [comment]
Some insights into the file preloading behaviour, after logging request to memfs.readFile for files which exist on disk, but have no content preloaded.
```
ensureBasicFiles -> getProgram
ensureSourceFile 'ast.ts' -> getProgram
NO CONTENT: ./node_modules/vscode-jsonrpc/lib/main.d.ts 
NO CONTENT: ./node_modules/opentracing/lib/index.d.ts 
NO CONTENT: ./node_modules/vscode-jsonrpc/lib/messages.d.ts 
NO CONTENT: ./node_modules/vscode-languageserver/lib/main.d.ts 
NO CONTENT: ./node_modules/@types/json-patch/index.d.ts 
NO CONTENT: ./node_modules/@reactivex/rxjs/dist/cjs/Rx.d.ts 
NO CONTENT: ./node_modules/vscode-languageserver-types/lib/main.d.ts 
NO CONTENT: ./node_modules/@types/sinon/index.d.ts 
publishDiagnostics 'ast.ts' -> getProgram -> 0 diagnostics
```

*`ast.ts` has no references, yet TS is already trying to load these modules.*

No harm done yet, but if I didOpen `typescript-service` after `ast.ts`, this happens:
```
didOpen 'typescript-service.ts' -> ensureReferencedFiles

ADDED ./node_modules/@reactivex/rxjs/dist/cjs/Rx.d.ts 
ADDED ./node_modules/@types/json-patch/index.d.ts 
ADDED ./node_modules/opentracing/lib/index.d.ts 
ADDED ./node_modules/vscode-languageserver/lib/main.d.ts 
ADDED ./node_modules/vscode-jsonrpc/lib/messages.d.ts 

ensureBasicFiles -> getProgram()

ADDED ./node_modules/vscode-jsonrpc/lib/main.d.ts 
ADDED ./node_modules/vscode-languageserver-types/lib/main.d.ts 

didOpen ensureReferencedFiles done 

ensureSourceFile 'typescript-service.ts' -> getProgram() 
publishDiagnostics 'typescript-service.ts' -> getProgram() -> 
[
File 'Rx.d.ts' is not a module
File 'json-patch/index.d.ts' is not a module
File 'opentracing/lib/index.d.ts' is not a module
File 'vscode-languageserver/lib/main.d.ts' is not a module
]
```

If I only open `typescript-service.ts` by itself, the files are loaded in time (no NO CONTENT log entries) and the diagnostics do not appear. 

This "TS fails to load modules after failing to load them once" issue might be why the tests in #261 are failing. If TS discovers these modules from package.json, then we might have to pre-fetch them before ensureReferencedFiles. Do you have an idea how this could be solved?

I did find one exception to this behaviour because I also logged requests for `@types/sinon/index.d.ts`: TS _does_ keep trying to load that file from memfs after initial failure. Perhaps the `@types` folder can be excluded from this extra pre-fetch.

**Comment by felixfbecker** [comment]
> No harm done yet

I actually think this is a serious issue. If files fail to load like this, that means other features like go-to-definition or references are probably affected too.

Could you clarify what you mean with "TS fails to load modules after failing to load them once"? What circumstances cause the issue to appear? Do you have an idea how to fix it? Could you give me a patch or steps to reproduce?

**Comment by tomv564** [comment]
I briefly tried to repro this using sourcegraph.com by hovering something in ast.ts followed by hovering an imported symbol in typescript-service.ts but was unsuccessful.

**Repro**: (in branch `remove-strict` although master should behave the same)
* initialise service
* didOpen src/ast.ts 
* didOpen src/typescript-service.ts (and wait briefly for diagnostics)

**Cause:**

TS might be caching the empty content we return for imported files, and we might not have a way to effectively 'bust' this cache.

**Next steps:**

Throwing an error when TS gets empty content reveals this stack trace:
```
Error: NO CONTENT /Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@types/sinon/index.d.ts
    at InMemoryFileSystem.readFile (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/lib/memfs.js:130:19)
    at InMemoryLanguageServiceHost.getScriptSnapshot (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/lib/project-manager.js:540:53)
    at HostCache.createEntry (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/typescript/lib/typescript.js:85679:44)
    at HostCache.getOrCreateEntryByPath (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/typescript/lib/typescript.js:85704:24)
    at HostCache.getOrCreateEntry (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/typescript/lib/typescript.js:85699:25)
    at Object.fileExists (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/typescript/lib/typescript.js:85952:38)
    at tryFile (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/typescript/lib/typescript.js:25159:28)
    at tryExtension (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/typescript/lib/typescript.js:25152:24)
    at tryAddingExtensions (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/typescript/lib/typescript.js:25145:24)
    at loadModuleFromFile (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/typescript/lib/typescript.js:25119:41) 
```

It would be helpful to know:
* How TS finds those imports before ensureReferencedFiles resolves them 
  * package.json, or after traversing the in-memory file structure?
* What is the behaviour of HostCache and can we bust this cache?

**Comment by felixfbecker** [comment]
Did throwing the error instead of returning an empty string break everything? Would have been nice if TS caught it and moves on without contaminating the cache.

I think our only chance is to fetch all contents TS could request for TS asks for them. I don't think there is a way to invalidate any internal cache - except `ProjectConfiguration.reset()` probably, which disposes the Program, Host and Service. We try to do that exactly with our calls to ensureOwnFiles, ensureReferencedFiles and fetching presumably-global TS files.

As I understand it, these files are fetched eventually, but TS somehow requests them before before that. Does the stack trace give any information what call triggered this (if a breakpoint is set there)?

**Comment by felixfbecker** [comment]
As for a Sourcegraph repro case, this _could_ be one: https://sourcegraph.com/github.com/angular/angular/-/blob/aio/aio-builds-setup/dockerbuild/scripts-js/test/clean-up/build-cleaner.spec.ts#L63:54

the `expect` return type is `any`, even though all the `jasmine` declarations are available to the Host and InMemoryFileSystem. In VS Code with tsserver it works.

**Comment by felixfbecker** [comment]
Can this be closed?

**Comment by tomv564** [comment]
Yep!
