### ISSUE TITLE
Need to handle diagnostics without file field

### ISSUE THREAD

**Issue by tomv564** [sourcegraph/javascript-typescript-langserver#239]
The language service is failing to return diagnostics and logging errors when compiler diagnostics are returned alongside file diagnostics.
 
These diagnostics (despite the typing of `ts.Diagnostic`) have no `file` field (typically just a code and a message).

To avoid exceptions handling those diagnostics, adding a  `tsDiagnostics.filter(f => !!f.file)` is needed before calling `convertTsDiagnostic` in `_publishDiagnostics`

**Comment by felixfbecker** [comment]
Could you report that as a bug to TypeScript as well? The interface doesn't mention that `file` is optional

**Comment by tomv564** [comment]
Technically, the field is specified :)
https://github.com/Microsoft/TypeScript/blob/2150a7796b0dfe83c5286755410e0fd1646ed86c/src/compiler/core.ts#L1235-L1251

**Comment by felixfbecker** [comment]
The declared type of the property is `SourceFile`, not `SourceFile | undefined`. TS' type system doesn't differentiate between present properties and `undefined` properties, if they had enabled `strictNullChecks` the code you linked would cause a compile error.

**Comment by felixfbecker** [comment]
Filed https://github.com/Microsoft/TypeScript/issues/15666

**Comment by tomv564** [comment]
Ah, just as I threw https://github.com/Microsoft/TypeScript/issues/15667 on the pile.

**Comment by tomv564** [comment]
I closed mine. Surprised they are not running with `strictNullChecks` already - my expectation was to find an `as Diagnostic` somewhere :)

**Comment by felixfbecker** [comment]
Yes, I am receiving so many `cannot read x of undefined` errors from _within_ the TS codebase that could probably be all solved with that flag.
