### ISSUE TITLE
Eslint Support

### ISSUE THREAD

**Issue by keeslinp** [sourcegraph/javascript-typescript-langserver#324]
Hey,

Is it possible to integrate Eslint with this language server? I've just started using this and I'm not sure how to configure things but it would be super useful to have that. On http://langserver.org/ it lists this library as having diagnostics, I'm just not sure how to use that.

Thanks!

**Comment by felixfbecker** [comment]
There is a dedicated ESLint language server here: https://github.com/Microsoft/vscode-eslint/tree/master/eslint-server

**Comment by keeslinp** [comment]
Thank you for the fast response!

**Comment by soywod** [comment]
The link has changed : https://github.com/Microsoft/vscode-eslint/tree/master/server. Btw I installed it on my machine, and put in my init.vim : 
```
let g:LanguageClient_serverCommands = {
  \ 'javascript': ['node', '/opt/vscode-eslint/server/out/eslintServer.js', '--stdio']
  \ }
```
But impossible to make it work (nothing is getting highlighted or linted), someone has already tried this ?

**Comment by myfreeweb** [comment]
Would be nice to have this server call into eslint/tslint. Do any clients even support multiple servers? LanguageClient-neovim doesn't.
