### ISSUE TITLE
Support Typescript Language Service plugins?

### ISSUE THREAD

**Issue by tomv564** [sourcegraph/javascript-typescript-langserver#326]
Since TS 2.2.2 there is support for plugins to tsserver.

I would like to be able to run the tslint plugin inside javascript-typescript-langserver, because:
* It re-uses the already-parsed SourceFiles (performance improvement)
* It automatically registers code fixes for lint diagnostics.

As they are implemented as wrappers to ts.LanguageService, all we should need to do is read the relevant settings from tsconfig and apply the plugin decorators whenever we construct a LanguageService.
The whole setup is documented at https://github.com/RyanCavanaugh/sample-ts-plugin.

Do you have any reservations against this? I may put together a PR for this to evaluate the cost

**Comment by felixfbecker** [comment]
Sounds great!
