### ISSUE TITLE
partialResults are sent when clientCapabilities do not support them

### ISSUE THREAD

**Issue by damieng** [sourcegraph/javascript-typescript-langserver#329]
Hooking up this language server to Atom right now and finding a ton of out-of-spec partialResult messages being returned. Wondering if this is a cause of some slow perf we're seeing but am unable to switch them off to see.

It looks like the intent was that the clientCapabilities has a streaming property which defines when these messages are supposed to be sent but it isn't yet honored.

**Comment by tomv564** [comment]
I brought this up in https://github.com/sourcegraph/javascript-typescript-langserver/issues/298 because I thought it would be a significant effort. 

Looking at the TODO mentioned in that issue (https://github.com/sourcegraph/javascript-typescript-langserver/blob/master/src/connection.ts#L257-L282) it does not look that hard to fix!

**Comment by felixfbecker** [comment]
I don't think that sending these notifications are a problem. VS Code sends a lot of non-specced notifications like `$/trace` and the server also resends `textDocument/publishDiagnostics` and those are not a problem. Message handling in the client shouldn't be the bottleneck or there is more likely something wrong with the client. That said, I don't have a problem with checking the flag there and would accept a PR, that's what it's for after all.

**Comment by tomv564** [comment]
I think this specific issue can be closed, the performance discussion continues in #331

**Comment by damieng** [comment]
I still think this is an issue. Emitting unwanted out-of-spec messages is quite annoying from the client side especially if you have debugging on, it makes it a real pain to see what's going on.  It's also a pretty easy fix - I have one incoming.

**Comment by felixfbecker** [comment]
It is already fixed in https://github.com/sourcegraph/javascript-typescript-langserver/commit/2b68b48eacc5261fec5ddaffedba3a2a6e2d9852

**Comment by damieng** [comment]
Great, thanks. I had that piece but didn't manage to get tests working.
