### ISSUE TITLE
How to use javascript-typescript-langserver in windows 

### ISSUE THREAD

**Issue by abramhum** [sourcegraph/javascript-typescript-langserver#355]
Hi:
I am a newbie to javascript-typescript-langserver, and recently I use sublime text3 and 
need to install LSP to trace Jquery Source Codes. My system environment is windows 10, 
and I have installed node.js, and use npm to download some projects. 
The main problem is I don't know how to use javascript-typescript-langserver in windows 10, 
since I didn't see some clear directives for windows user, and how to make it work well 
under windows system to make it can work with sublime text.
Is any one know how to do that, thanks a lot.

**Comment by felixfbecker** [comment]
This language server supports Windows, you just need to install an LSP extension for Sublime

**Comment by tomv564** [comment]
@abramhum the configuration steps for this server are described in the LSP package's [documentation](https://lsp.readthedocs.io/en/latest/#language-specific-setup), and a [troubleshooting](https://lsp.readthedocs.io/en/latest/#troubleshooting) has been added to help you if it doesn't work "out of the box".

The only windows-specific configuration is changing the `"command"` setting to `javascript-typescript-stdio.cmd` in LSP.sublime-settings.

If you get stuck, please create an issue in the [LSP repo on github](https://github.com/tomv564/LSP), with a clear explanation of what is not working and logs from the Sublime console .
