### ISSUE TITLE
Requests are delayed until start-up processing completes

### ISSUE THREAD

**Issue by damieng** [sourcegraph/javascript-typescript-langserver#367]
If you start the language server and then decide say 5 seconds in to shut down you can be waiting a minute or so for the language server to finish analyzing files and publishing diagnostics before it responds to the shutdown request.

For language clients this is troublesome as either they have to hang on shutdown or forcefully terminate the process.

**Comment by tomv564** [comment]
It looks like support exists for cancelling outstanding requests (https://github.com/sourcegraph/javascript-typescript-langserver/blob/d047d674e3cdb8e58df8f318efd2f86732bb7e94/src/connection.ts#L198-L215), does that address the issue?

**Comment by damieng** [comment]
In this case though there isn't any outstanding request as far as I know.  It's just a bunch of post-initialization activity.

**Comment by felixfbecker** [comment]
Yeah this is not how it should work. Either the event loop is blocked or the shutdown handler is waiting for something.

**Comment by damieng** [comment]
It appears all lsp messages are being blocked. On a large project we are seeing for example an outline view request take 300 seconds+ to process while various logMessages indicate it's finding package.json's in node_modules etc.

**Comment by damieng** [comment]
Any pointers to where I should start digging in if I want to work on this one?

**Comment by felixfbecker** [comment]
So the language server first has to load all files before it can answer any request. But it should never take 300s+. If you suspect it's the package.json detection there is a way to experiment with using async RxJS schedulers to yield control back to the event loop between each event and not block it.

**Comment by damieng** [comment]
Might also be this https://github.com/atom/ide-typescript/issues/95

**Comment by felixfbecker** [comment]
Also check out https://github.com/sourcegraph/javascript-typescript-langserver#debugging-performance-with-opentracing
