### ISSUE TITLE
Question about NodeJS modules completion

### ISSUE THREAD

**Issue by asilvadesigns** [sourcegraph/javascript-typescript-langserver#375]
Forgive me for the noob question, I am using this langserver within neovim using the LSP provider. All works well, but when editing javascript files using node modules, there is no method completion. I was curious if that is implemented here or that would be an issue with the neovim LSP provider.

Thanks!

**Comment by felixfbecker** [comment]
For JavaScript, the language service expects the shape of dependencies to be declared in typings declarations. Try installing `@types/` packages for your dependencies.

**Comment by GodefroyClair** [comment]
Hi,
I have the same question asasilvadesigns regarding autocompletion for my dependencies in node.
I am not very familiar with typescript. When you say :
`try installing @types/ packages for your dependencies`
does it mean that for each dependencies I have to install the typescipt dependency ? Where can I find more documentation about the installation with neovim?
Thx!
