### ISSUE TITLE
About TypeScript 2.3 --checkJs

### ISSUE THREAD

**Issue by Dcryfm** [sourcegraph/javascript-typescript-langserver#393]
Please consider supporting [Type Checking JavaScript Files](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files)

**Comment by cancerberoSgx** [comment]
Since typescript supports jsdoc - closure annotations this feature sis very important for those of us that cannot migrate to typescript and must continue working in vanilla javascript. Please Please so support --checkJs and --allowJs. Thanks

**Comment by felixfbecker** [comment]
@cancerberoSgx this depends on updating to the latest TypeScript version - feel free to take #379 or #385 over the finish line

**Comment by felixfbecker** [comment]
Actually, we already use TS 2.4. So this should work.
