### ISSUE TITLE
Hover information for type signatures with callbacks is incorrect

### ISSUE THREAD

**Issue by danr** [sourcegraph/javascript-typescript-langserver#413]
https://github.com/sourcegraph/javascript-typescript-langserver/blob/d02f2340b22000cfdcdace7c32d1dad71a439063/src/typescript-service.ts#L612

This should be a non-greedy `+`, as in `\(.+?\)`.
Consider the string
```
(local function) act(handle: () => void): void
``` 
Right now this is incorrectly chopped to 
```
 => void): void
```
instead of the correct
```
act(handle: () => void): void
``` 
HTH

**Comment by felixfbecker** [comment]
Great catch! Wanna submit a PR?
