### ISSUE TITLE
Information from server provider is not correct

### ISSUE THREAD

**Issue by semanser** [sourcegraph/javascript-typescript-langserver#423]
Hey. Not sure that is the problem with javascript-typescript-langserver, but I will start from this repository.

I have installed everything correctly but looks like `javascript-typescript-langserver` does not work as expected. Autocompletion is garbaged with some random stuff, goto definition is not working with all variables etc.

For the demonstration, I created simple array variable inside a class method.

NeoVim:
![screen shot 2018-01-07 at 22 49 55](https://user-images.githubusercontent.com/4020045/34654022-3ae5a676-f3fe-11e7-8464-40f9d179855f.png)

However, in VSCode everything looks good:
![screen shot 2018-01-07 at 22 49 23](https://user-images.githubusercontent.com/4020045/34654028-587d6afc-f3fe-11e7-80ff-62e188f3dc66.png)

**What can be the problem? Does this server implementation work with ES6?
Also, is it possible to run VSCode language server beside the NeoVim?**

_NeoVim v0.2.2
Python3 enabled
Latest Deoplete as a completion engine_

**Comment by aoswalt** [comment]
I am having this same issue and have not been able to find a cause or resolution.

**Comment by GodefroyClair** [comment]
Here too

**Comment by felixfbecker** [comment]
This looks like a dupliate of #432
