### ISSUE TITLE
Ability to provide default tsconfig 

### ISSUE THREAD

**Issue by damieng** [sourcegraph/javascript-typescript-langserver#433]
It would be great if we could supply a default tsconfig block as part of the initialize request that would override this one;

https://github.com/sourcegraph/javascript-typescript-langserver/blob/a0c47d452ef3d7612100a0fda4072bee20f9d333/src/project-manager.ts#L125

(Would a PR for this be accepted?)

**Comment by felixfbecker** [comment]
What's the use case?

**Comment by damieng** [comment]
We'd like to be able to offer users some default choices especially around JS where they don't expect to have to create a jsconfig.json file.  

Some examples:

- [adding experimentalDecorators](https://github.com/atom/ide-typescript/issues/30)
- [using ES2015 imports](https://github.com/atom/ide-typescript/issues/39)

**Comment by felixfbecker** [comment]
I think that would make sense to enable for all consumers of the language server, don't you think?

**Comment by damieng** [comment]
Yes, it would be my proposal that anyone could send the extra payload along with initialization, perhaps under a tsConfig or jsConfig within initializationOptions?

e.g.

```json
{
   "processId":13704,
   "rootPath":"C:\\Users\\damie\\github\\atom-languageclient\\",
   "rootUri":"file:///C:/Users/damie/github/atom-languageclient/",
   "initializationOptions":{
     "tsConfig": {
       "compilerOptions": {
         "module": "ts.ModuleKind.CommonJS",
         "allowNonTsExtensions": false,
         "allowJs": true
       }
     }
   },
   "capabilities":{
      "workspace":{
         "applyEdit":true,
         "workspaceEdit":{
            "documentChanges":true
         }
    }
}
```

**Comment by felixfbecker** [comment]
What I mean is: if the goal is to have more sensible defaults without user configuration (jsconfig), then why not update the snippet you linked in the language server instead of requiring every client to come up with and hardcode a default

**Comment by damieng** [comment]
I was intending on exposing the import module type as a setting in my package so the user can choose between import/require in this particular case.  I'm reasonably sure if we switch it from require to import somebody else will complain.

**Comment by felixfbecker** [comment]
Does `require` stop working when you enable `module: es6`?

If the goal is to allow configuration of jsconfig without a jsconfig.json this should probably go through `workspace/didChangeConfiguration` instead of `initializationOptions`

**Comment by abeMedia** [comment]
Any update on this?
