### ISSUE TITLE
High CPU usage when there're recursive links

### ISSUE THREAD

**Issue by chemzqm** [sourcegraph/javascript-typescript-langserver#453]
When I'm developing a plugin for neovim, the file tree would like this:
```
~/plug.nvim
❯ tree .
.
├── Readme.md
├── index.js
├── package.json
└── rplugin
    └── node
        └── plug.nvim -> ../..

3 directories, 3 files
```
there's a link `plug.nvim` that link to parent folder of parent folder.
This structor would cause javascript-typescript-langserver take 100% CPU usage very quickly.
It would be great if javascript-typescript-langserver could detect recursive link.

To reproduce this issue, you can download the code from https://github.com/neoclide/npm.nvim

**Comment by chemzqm** [comment]
@felixfbecker just don't want to put the code into `rplugin/node`, it's easier to work with by using the recursive symlink.

**Comment by chemzqm** [comment]
Same issue with typescript, I found set `follow: false` to glob module could solve this problem.

**Comment by felixfbecker** [comment]
Yes, but then symlinks would not work at all, including `npm link`. I would rather have symlink support without support for the edge case of recursive symlinks than no symlink support

**Comment by chemzqm** [comment]
@felixfbecker I can set the ignore option of glob to avoid this problem, maybe it could be exported as an option.

**Comment by chemzqm** [comment]
The ignore doesn't works, but I have find a way to not using recursive link.
Thanks for reply.

**Comment by erkie** [comment]
@felixfbecker this seems to be a fairly common issue, see the mentioned issues above. Recursive symlinks might be a bad thing™ but some build systems do generate them in the wild. How would you suggest to get around this when it does occur?
