### ISSUE TITLE
cannot install on windows due to postinstall script

### ISSUE THREAD

**Issue by prabirshrestha** [sourcegraph/javascript-typescript-langserver#49]
Cannot use npm install on windows since it has a post install script that runs bash and bash in not available on windows.

```json
 "postinstall": "bash bin/postinstall"`
```

Rather than compiling during postinstall why not include only .d.ts and the compiled js in npm package?

**Comment by alexsaveliev** [comment]
@prabirshrestha I'll try to take care of this one. My goal was to make it able to use the code via npm package (`"javascript-typescript-langserver": "^1.0.1"`) and via Github URL (`"javascript-typescript-langserver": "git+https://github.com/sourcegraph/javascript-typescript-langserver"`). I am using Cygwin locally so haven't noticed the issue.

**Comment by prabirshrestha** [comment]
That makes sense now. Then would it be possible to write the postinstall script in javascript and run it via node since everyone will most likely have node installed if they are using npm install.

**Comment by prabirshrestha** [comment]
Seems like v1.0.1 from master doesn't even compile on windows if I remove postinstall.

![image](https://cloud.githubusercontent.com/assets/287744/21578733/64fb9e54-cf40-11e6-87a0-50aaad04ac5e.png)
