### ISSUE TITLE
Upgrade to TypeScript 3?

### ISSUE THREAD

**Issue by j-f1** [sourcegraph/javascript-typescript-langserver#495]
[TypeScript 3.0](https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/) was recently released. I’d like to use some of its features in a new project. Would it be possible to upgrade this package’s version of TypeScript so people can use the new features without them breaking IDEs?

**Comment by felixfbecker** [comment]
PR welcome :)

**Comment by keyboardDrummer** [comment]
PR: https://github.com/sourcegraph/javascript-typescript-langserver/pull/500
