### ISSUE TITLE
babel function bind

### ISSUE THREAD

**Issue by delfick** [sourcegraph/javascript-typescript-langserver#496]
Hello,

Is it possible to make this langserver understand https://babeljs.io/docs/en/babel-plugin-transform-function-bind.html ?

I have neovim setup to use https://github.com/autozimu/LanguageClient-neovim and it says where I use `this::function(...) { ... }` or `::this.somefunction` are errors.

Thanks

**Comment by felixfbecker** [comment]
Unfortunately no, not until TypeScript supports it.
