### ISSUE TITLE
support textDocument/didOpen in non strict mode

### ISSUE THREAD

**Issue by prabirshrestha** [sourcegraph/javascript-typescript-langserver#51]
I'm working on a generic LSP client for vim and would like to automatically call `textDocument/didOpen` when a typescript file is opened. Would it be possible to support it even when using non-strict mode? I would want to avoid writing code like if typescript don't send textDocument/didOpen. Currently I get `{"error": "code": -32601, "message" "Unhandled method textDocument/didOpen"}}`.

I also noticed that first time I call any of the methods like `textDocument/definition` or `textDocument/references` or `textDocument/documentSymbol` it is very slow. If `textDocument/didOpen` is supported the language server could use it as a way to also preload the references and symbols so it would be fast.

**Comment by beyang** [comment]
Yep, should be possible. I'll take a look this week.

**Comment by alexsaveliev** [comment]
Hey, @prabirshrestha 

>  Would it be possible to support it even when using non-strict mode? 

`textDocument/didOpen` should work in non-strict mode already. I'm using Visual Studio Code that sends such a requests and they going through without an error (with the following difference from your request - we do not perform references/symbols preloading on `didOpen`, we are updating the source code data and invalidating TypeScript internals to re-build refs/symbols when they will be requested by `definition`, `references` or `documentSymbol`)

Could you please provide some more information regarding how do you invoke `textDocument/didOpen` requests, what are the JSON-RPC request's arguments (and the overall request flow, if possible)?

Thanks!

**Comment by prabirshrestha** [comment]
I don't perform references/symbols preloading on didOpen. It was a suggestion if the server should preload it instead. I noticed that going to references takes almost 5 seconds for the first time, after that it is fast. (This should had been a different issue. Sorry for the confusion here).

Here is the rpc request: (`text` is the actual source code of the file and contains `\n`.)

```json
{
  "id": 2,
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "textDocument": {
      "uri": "file:///D:/tmp/javascript-typescript-langserver/src/util.ts",
      "version": 1,
      "langaugeId": "typescript",
      "text": "...."
    }
  }
}
```

I also tried with the following.

```json
{
  "id": 2,
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "uri": "file:///D:/tmp/javascript-typescript-langserver/src/util.ts",
    "version": 1,
    "langaugeId": "typescript",
    "text": "...."
  }
}
```

Would be good if `javascript-typescript-langserver` supported `--trace ~/langserver.log` similar too `langserver-go`. I had been avoiding writing log for my `vim-lsp` till now since golang supported it.

**Comment by prabirshrestha** [comment]
Found this code while digging in `go-langserver`. Would need something similar. https://github.com/sourcegraph/go-langserver/blob/a76055aa3fa9c859b369acd615d130e697876e95/langserver/handler.go#L163-L174

```go
// PERF: Kick off a workspace/symbol in the background to warm up the server
if yes, _ := strconv.ParseBool(envWarmupOnInitialize); yes {
	go func() {
		ctx, cancel := context.WithDeadline(ctx, time.Now().Add(30*time.Second))
		defer cancel()
		_, _ = h.handleWorkspaceSymbol(ctx, conn, req, lsp.WorkspaceSymbolParams{
			Query: "",
			Limit: 100,
		})
	}()
}
```

**Comment by alexsaveliev** [comment]
Regarding `Unhandled method` error, the reason is the same as in #56, you should remove `id` from `textDocument/did...` notification messages

**Comment by prabirshrestha** [comment]
It works
