### ISSUE TITLE
Don't commit compiled JS

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/javascript-typescript-langserver#58]
General pattern for TS libraries is to commit only .ts source and only publish .js, .d.ts and .js.map to npm. We should do it that way to prevent the risk of compilation results and source getting out of sync. In Sourcegraph we install from npm, we have control over the publish process so we can always do pre-releases and locally we can use `npm link`, so there seems to be no need for having the compiled files on GH, which is kind of like committing binaries.

**Comment by alexsaveliev** [comment]
@felixfbecker Yesterday I've said that there are no places when somebody uses GitHub-style dependency left. Today we got one :smile: , see:
https://github.com/sourcegraph/sourcegraph/pull/3104/files#diff-32dd941b31b9224e0da05d34b31c9282

**Comment by felixfbecker** [comment]
but why? if this is supposed to get merged, it should use a version reference. If it is used in local development, `npm link` should be used
