### ISSUE TITLE
Cannot `npm install` this from behind a proxy

### ISSUE THREAD

**Issue by bolinfest** [sourcegraph/javascript-typescript-langserver#69]
I am trying to install the language server standalone on a Linux machine that is behind a proxy. I believe the reason it is failing is because the NPM `vscode` module (which confusingly lives in a repo named [`vscode-extension-vscode`](https://github.com/Microsoft/vscode-extension-vscode)) has a [`bin/install`](https://github.com/Microsoft/vscode-extension-vscode/blob/master/bin/install) script that it runs, which is called by your [`bin/postinstall`](https://github.com/sourcegraph/javascript-typescript-langserver/blob/v1.0.1/bin/postinstall#L5) script.

The issue is that `bin/install` makes requests to things like [raw.githubusercontent.com](https://github.com/Microsoft/vscode-extension-vscode/blob/v1.0.1/bin/install#L64) and [vscode-update.azurewebsites.net](https://github.com/Microsoft/vscode-extension-vscode/blob/v1.0.1/bin/install#L69). There's no obvious place for me to specify which proxy I should use when making these requests, so everything fails.

If you're curious how I was even able to run `npm install javascript-typescript-langserver` in the first place, it is because `npm` lets you configure a proxy as follows:

```
npm config set proxy http://theproxy:port
npm config set https-proxy http://theproxy:port
```

**Comment by felixfbecker** [comment]
@beyang do you know why we depend on vscode?

**Comment by beyang** [comment]
@bolinfest thanks for filing this issue and the other one on the Go language server. The vscode dependency has been removed and should be available in the next version @felixfbecker cuts to npmjs.com.

One of our main goals in open-sourcing these language servers is to make them the standard language backends for developers of editors and editor extensions. I'm a fan of your past work and was wondering if you'd be up to chat about what you'd like to see in terms of future feature development. Happy to chat live or continue the discussion in an issue thread.
