### ISSUE TITLE
Allow to run in TCP mode without cluster

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/javascript-typescript-langserver#78]
Every worker runs in a separate process so it's hard to attach a debugger.
TCP and cluster code should not be in the same file.

**Comment by beyang** [comment]
Could you just forward the `--debug` flag, if set, to child process in some way? In the original cluster implementation, it was still possible to use the browser-based JS debugger by passing the associated debugger port of the subprocess. When testing in dev, I would limit the number of workers to 1 (in this case 2) to ensure I would always attach to an active worker.

**Comment by felixfbecker** [comment]
I do - but every worker has it's own port, so you first need to start the master, then copy+paste the logged port and attach to that. It would be far easier if I could just F5 to launch a single worker

**Comment by beyang** [comment]
I see. The other thing you could do is limit the number of workers to 1, so that there is just one worker receiving all request. That way it should always expose its debugger on the same port.
