### ISSUE TITLE
Server allocates excessive inodes

### ISSUE THREAD

**Issue by renfredxh** [sourcegraph/javascript-typescript-langserver#80]
The TS langserver has been excessively allocating fs inodes on the sourcegraph production cluster, eventually depleting the max inode limit and causing other issues. 

When inspecting in the production pod, we found 5.4 million files within the `tsjs-yarn*` directories in `/tmp`.

The [graph](https://prometheus.sgdev.org/graph?g0.range_input=2d&g0.expr=container_fs_inodes_total%7Bpod_name!%3D%22%22%7D&g0.tab=0) below is tracking the inode count for the production servers. The two tall lines are from the typescript lang pods. The point where it begins increasing is approximately Feb 24 at 23:00 GMT.

![image](https://cloud.githubusercontent.com/assets/3800339/23337356/9fc487fe-fb9f-11e6-80ea-dc74cb11603f.png)

/cc @beyang

**Comment by felixfbecker** [comment]
This issue was moved to sourcegraph/sourcegraph#4420
